%require "3.2"
%language "c++"
%define api.value.type variant
%define api.token.constructor
%define api.parser.class {Parser}
%define api.namespace {LC}
%locations
%define api.location.file "grammar.loc.hpp"
%lex-param {yyscan_t scanner}
%parse-param {yyscan_t scanner}
%parse-param {std::optional<std::variant<ParseResultVariant, syntax_error>>* result}
%header "grammar.tab.hpp"

%token LPAREN
%token RPAREN
%token DOT
%token SEMI
%token LT
%token GT
%token SYM_4
%token KW_const
%token SYM_3
%token KW_id
%token SYM_2
%token KW_l
%token SYM_1
%token <std::string> IDENT
%token <int32_t> CHAR
%token <double> DOUBLE
%token <long> INTEGER
%token <std::string> STRING
%token <std::string> CUSTOM_SpecialBegin
%token <std::string> CUSTOM_SpecialEnd

%code requires {
    #include <string_view>
    #include <optional>
    #include <variant>
    #include "Absyn.hpp"

    using yyscan_t = void*;

    namespace LC {

    using ParseResultVariant = std::variant<LC::Program>;

    }  // namespace LC
}

%nterm <Expr> Expr
%nterm <Program> Program
%nterm <Expr> Expr1
%nterm <Expr> Expr2
%nterm <ListExpr> ListExpr

%code provides {
    namespace LC {

    using ParseResultOrError =
        std::variant<ParseResultVariant, Parser::syntax_error>;
    ParseResultOrError Parse(FILE* file, std::string* optFilename = nullptr);
    ParseResultOrError Parse(std::string_view str, std::string* optFilename = nullptr);
    std::string_view ParsedNodeName(const ParseResultVariant&);

    template <class T>
    std::variant<T, Parser::syntax_error>
    EnsureParsedType(ParseResultOrError&& parsed, std::string* optFilename, optFilename) {
        if (auto* err = std::get_if<Parser::syntax_error>(&parsed))
            return std::move(*err);
        auto& var = std::get<ParseResultVariant>(parsed);
        if (auto* target = std::get_if<T>(&var))
            return std::move(*target);
        std::string msg = "Unexpected syntax: tried to parse ";
        msg
            .append(reflection::SyntaxNodeName<T>)
            .append(", but got ")
            .append(ParsedNodeName(var));
        return Parser::syntax_error(location({optFilename, 1, 1}, {optFilename, 1, 1}), msg);
    }

    template <class T>
    std::variant<T, Parser::syntax_error> ParseAs(FILE* file, std::string* optFilename = nullptr) {
        static_assert(reflection::IsParserEntrypoint<T>,
            "Cannot parse this class");
        return EnsureParsedType<T>(Parse(file, optFilename), optFilename);
    }
    template <class T>
    std::variant<T, Parser::syntax_error> ParseAs(std::string_view str, std::string* optFilename = nullptr) {
        static_assert(reflection::IsParserEntrypoint<T>,
            "Cannot parse this class");
        return EnsureParsedType<T>(Parse(str, optFilename), optFilename);
    }

    }  // namespace LC
}

%code {
    extern LC::Parser::symbol_type LClex(yyscan_t scanner);

    namespace LC {

    static inline Parser::symbol_type yylex(yyscan_t scanner) {
        return LClex(scanner);
    }

    }  // namespace LC
}

%start __start__

%%

__start__
    : Program YYEOF { *result = {{ParseResultVariant(std::move($1))}}; }
    | error YYEOF { if (!*result) *result = {{syntax_error(@1, "Lexical error")}}; }
    ;

Expr
    : /* _ */ Expr1 { $$ = std::move($1); }
    | /* Abstraction */ KW_l IDENT DOT Expr { $$.emplace<Abstraction>(@$, std::move($2), std::move($4)); }
    | /* StringExpr */ SYM_1 STRING { $$.emplace<StringExpr>(@$, std::move($2)); }
    | /* IntegerExpr */ SYM_2 INTEGER { $$.emplace<IntegerExpr>(@$, std::move($2)); }
    | /* DoubleExpr */ SYM_3 DOUBLE { $$.emplace<DoubleExpr>(@$, std::move($2)); }
    | /* CharExpr */ SYM_4 CHAR { $$.emplace<CharExpr>(@$, std::move($2)); }
    | /* SpecialExpr */ CUSTOM_SpecialBegin Expr CUSTOM_SpecialEnd { $$.emplace<SpecialExpr>(@$, std::move($1), std::move($2), std::move($3)); }
    ;

Program
    : /* AProgram */ ListExpr { $$.emplace<AProgram>(@$, std::move($1)); }
    ;

Expr1
    : /* _ */ Expr2 { $$ = std::move($1); }
    | /* Application */ Expr1 Expr2 { $$.emplace<Application>($@, std::move($1), std::move($2)); }
    ;

Expr2
    : /* _ */ LPAREN Expr RPAREN { $$ = std::move($2); }
    | /* Variable */ IDENT { $$.emplace<Variable>(@$, std::move($1)); }
    | /* id */ KW_id LT IDENT GT { $$ = make_id(@$, std::move($3)); }
    | /* const */ KW_const LT IDENT GT { $$ = make_const(@$, std::move($3)); }
    ;

ListExpr
    : /* [] */ /* empty */ { $$.loc = @$; }
    | /* (:[]) */ Expr { $$.push_front(std::move($1)); $$.loc = @$; }
    | /* (:) */ Expr SEMI ListExpr { $$ = std::move($3); $$.push_front(std::move($1)); $$.loc = @$; }
    ;

%%

namespace LC {

// optFilename is not owned by the lexer.
class LCScanner {
    yyscan_t scanner;
    LCScanner(std::string* optFilename);

public:
    LCScanner(FILE* file, std::string* optFilename);
    LCScanner(std::string_view str, std::string* optFilename);
    yyscan_t FlexScanner() const;
    ~LCScanner();
};

void Parser::error(const location& loc, const std::string& msg) {
    *result = {{syntax_error(loc, msg)}};
}

static ParseResultOrError Parse(const LCScanner& scanner, std::string* optFilename) {
    std::optional<ParseResultOrError> res;
    Parser parser(scanner.FlexScanner(), &res);
    parser.parse();
    if (!res) return {Parser::syntax_error("")};
    return std::move(*res);
}

ParseResultOrError Parse(FILE* file, std::string* optFilename) {
    return Parse(LCScanner(file, optFilename));
}

ParseResultOrError Parse(std::string_view str, std::string* optFilename) {
    return Parse(LCScanner(str, optFilename));
}

std::string_view ParsedNodeName(const ParseResultVariant& var) {
    return std::visit([](const auto& node) -> std::string_view {
        return reflection::SyntaxNodeName<std::decay_t<decltype(node)>>;
    }, var);
}

}  // namespace LC
